# @package _global_

_moai_:
  _definitions_:
    _collections_:
      _optimizers_:
        optim_nerf: &optim_nerf
          _type_: adamw # adam
          _params_:
            lr: 1e-3
            amsgrad: true
            eps: 1e-12
            weight_decay: 1e-5 # 0.1 # 1e-6
            foreach: true # false
            capturable: false
            differentiable: false
            fused: false # true
          _groups_: [model]
      _objectives_:
        color_loss:
          L2:
           gt: [mask]
           pred: [reconstructed_color]
           _weight_: [1.0]              
           _reduction_: [sum]
           _out_: [L2]