
defaultContentLanguage = "en"
enableRobotsTXT = "true"
pagination.pagerSize =	100
summaryLength = 80
outputs.home = ["HTML", "RSS", "JSON"]
paginate = 36

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"
  article = "articles"
  paper = "papers"

[markup]
  [markup.tableOfContents]
    endLevel = 4
    startLevel = 1  

[imaging]
  anchor = 'Center'

[sitemap]
  changefreq = 'always'
  filename = 'sitemap.xml'
  priority = 0.5


[related]
  threshold = 0
  toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 20

    [[related.indices]]
        name = "date"
        weight = 10

    [[related.indices]]
      applyFilter = false
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10