# config/_default/menus.toml

[[main]]
  pre = "github"
  name = "GitHub"
  url = "https://github.com/moverseai/snap"
  weight = 1


# [[main]]
  # name = "Articles"
  # pageRef = "articles"
  # weight = 10

# [[main]]
  # name = "Papers"
  # pageRef = "papers"
  # weight = 20

[[main]]
  name = "2021"
  pageRef = "papers2021"
  weight = 20

[[main]]
  name = "ICCV 2021"
  parent = "2021"
  pageRef = "tags/iccv21"
  weight = 21

[[main]]
  name = "SIGGRAPH 2021"
  parent = "2021"
  pageRef = "tags/siggraph21"
  weight = 22

[[main]]
  name = "CVPR 2021"
  parent = "2021"
  pageRef = "tags/cvpr21"
  weight = 23

[[main]]
  name = "NeurIPS 2021"
  parent = "2021"
  pageRef = "tags/neurips21"
  weight = 24

[[main]]
  name = "SIGGRAPH Asia 2021"
  parent = "2021"
  pageRef = "tags/siggraph_asia21"
  weight = 25

[[main]]
  name = "arXiv 2021"
  parent = "2021"
  pageRef = "tags/arxiv21"
  weight = 26


[[main]]
  name = "2022"
  pageRef = "papers2022"
  weight = 30

[[main]]
  name = "CVPR 2022"
  parent = "2022"
  pageRef = "tags/cvpr22"
  weight = 31

[[main]]
  name = "SIGGRAPH 2022"
  parent = "2022"
  pageRef = "tags/siggraph22"
  weight = 32

[[main]]
  name = "3DV 2022"
  parent = "2022"
  pageRef = "tags/3dv22"
  weight = 33

[[main]]
  name = "ECCV 2022"
  parent = "2022"
  pageRef = "tags/eccv22"
  weight = 34

[[main]]
  name = "SIGGRAPH Asia 2022"
  parent = "2022"
  pageRef = "tags/siggraph_asia22"
  weight = 35

[[main]]
  name = "TPAMI 2022"
  parent = "2022"
  pageRef = "tags/tpami22"
  weight = 36

[[main]]
  name = "arXiv 2022"
  parent = "2022"
  pageRef = "tags/arxiv22"
  weight = 37


[[main]]
  name = "2023"
  pageRef = "papers2023"
  weight = 40

[[main]]
  name = "ACM Multimedia 2023"
  parent = "2023"
  pageRef = "tags/acmmm23"
  weight = 41

[[main]]
  name = "SCA 2023"
  parent = "2023"
  pageRef = "tags/sca23"
  weight = 42

[[main]]
  name = "CVPR 2023"
  parent = "2023"
  pageRef = "tags/cvpr23"
  weight = 43

[[main]]
  name = "SIGGRAPH 2023"
  parent = "2023"
  pageRef = "tags/siggraph23"
  weight = 44

[[main]]
  name = "ICCV 2023"
  parent = "2023"
  pageRef = "tags/iccv23"
  weight = 45

[[main]]
  name = "TPAMI 2023"
  parent = "2023"
  pageRef = "tags/tpami23"
  weight = 46

[[main]]
  name = "TVCG 2023"
  parent = "2023"
  pageRef = "tags/tvcg23"
  weight = 47

[[main]]
  name = "2024"
  pageRef = "papers2024"
  weight = 50

[[main]]
  name = "ToG 2024"
  parent = "2024"
  pageRef = "tags/tog24"
  weight = 51

[[main]]
  name = "TPAMI 2024"
  parent = "2024"
  pageRef = "tags/tpami24"
  weight = 52

# [[main]]
  # name = "About"
  # pageRef = "about"
  # weight = 25

# [[footer]]
  # name = "Privacy"
  # url = "https://external-link"

# config/_default/menus.toml

[[subnavigation]]
  name = "NeRF"
  pageRef = "tags/nerf"
  weight = 10

[[subnavigation]]
  name = "SMPL"
  pageRef = "tags/smpl"
  weight = 11

[[subnavigation]]
  name = "SMPL-X"
  pageRef = "tags/smplx"
  weight = 12

[[subnavigation]]
  name = "Skeleton"
  pageRef = "tags/skeleton"
  weight = 13

[[subnavigation]]
  name = "GHUM"
  pageRef = "tags/ghum"
  weight = 14

[[subnavigation]]
  name = "Generalized"
  pageRef = "tags/generalized"
  weight = 15

[[subnavigation]]
  name = "SDF"
  pageRef = "tags/sdf"
  weight = 16

[[subnavigation]]
  name = "Texture"
  pageRef = "tags/texture"
  weight = 17

[[subnavigation]]
  name = "Deformation"
  pageRef = "tags/deformation"
  weight = 18

[[subnavigation]]
  name = "Monocular"
  pageRef = "tags/monocular"
  weight = 19

[[subnavigation]]
  name = "Multiperson"
  pageRef = "tags/multiperson"
  weight = 20

[[subnavigation]]
  name = "Relight"
  pageRef = "tags/relight"
  weight = 21