# @package _global_

SH_DEGREE: ???
NUM_SPLATS:
  - 10475
  - 41853
  - 167333
SPLATS_PATH: ???

model:
  parameters:
    initializers:
      initialize_splats:
        data_path: ${SPLATS_PATH}
    groups:
  #     model3:
  #       modules:
  #         - uncertainty_field
  #       # parameters:
  #       #   - preproc.named_params.latent # NOTE: required
      # model2:
      #   # modules:
      #     # - tcnn_encoding_fully_fused_mlp # tcnn_encoding_mlp
      #     # - uncertainty_field
      #   monads:
      #     # - nerf_postproc.gaussian_splat_parameters
      #     - nerf_preproc.gaussian_splat_parameters
      #   # parameters:
      #   #   - preproc.named_params.offsets
      #   #   - preproc.named_params.latent # NOTE: required
      model_groups1:  
        groups:
          rotation:
            parameters:
              - nerf_preproc.gaussian_splat_parameters.rotation
            lr: 0.001 # ${nerf_LR} # 1e-2
          opacity:
            parameters:
              - nerf_preproc.gaussian_splat_parameters.opacity
            lr: 0.05 # ${nerf_LR} # 1e-2
          scaling:
            parameters:
              - nerf_preproc.gaussian_splat_parameters.scaling
            lr: 0.005 # ${nerf_LR} # 1e-2
          spherical_harmonics:
            parameters:
              - nerf_preproc.gaussian_splat_parameters.spherical_harmonics_dc
            lr: 0.0025 # ${nerf_LR} # 1e-2
          positions:
            parameters:
              - preproc.named_params.offsets
            lr: 1e-3
      model1:
        parameters:
          - preproc.named_params.offsets
      model2:
        parameters:
          - nerf_preproc.gaussian_splat_parameters.rotation
          - nerf_preproc.gaussian_splat_parameters.scaling
      model3:
        parameters:
          - nerf_preproc.gaussian_splat_parameters.spherical_harmonics_dc
          # - nerf_preproc.gaussian_splat_parameters.spherical_harmonics_d1
          # - nerf_preproc.gaussian_splat_parameters.spherical_harmonics_d2
          # - nerf_preproc.gaussian_splat_parameters.spherical_harmonics_d3
          - nerf_preproc.gaussian_splat_parameters.opacity
      model_groups2:  
        groups:
          dc:
            parameters:
              - nerf_preproc.gaussian_splat_parameters.opacity
              - nerf_preproc.gaussian_splat_parameters.spherical_harmonics_dc
            lr: ${nerf_LR}
          d1:
            parameters:
              - nerf_preproc.gaussian_splat_parameters.spherical_harmonics_d1
            lr: ${sh_LR} # 0.05 # ${nerf_LR} # 1e-2
          # d2:
          #   parameters:
          #     - nerf_preproc.gaussian_splat_parameters.spherical_harmonics_d2
          #   lr: ${sh_LR} # 0.01 # ${nerf_LR} # 1e-2
          # d3:
          #   parameters:
          #     - nerf_preproc.gaussian_splat_parameters.spherical_harmonics_d3
          #   lr: ${sh_LR} # 0.005 # ${nerf_LR} # 1e-2      
      model_groups4:  
        groups:
          rotation:
            parameters:
              - nerf_preproc.gaussian_splat_parameters.rotation
            lr: 0.01 # ${nerf_LR} # 1e-2
          opacity:
            parameters:
              - nerf_preproc.gaussian_splat_parameters.opacity
            lr: 0.05 # ${nerf_LR} # 1e-2
          scaling:
            parameters:
              - nerf_preproc.gaussian_splat_parameters.scaling
            lr: 0.05 # ${nerf_LR} # 1e-2
          spherical_harmonics:
            parameters:
              - nerf_preproc.gaussian_splat_parameters.spherical_harmonics_dc
            lr: 0.025 # ${nerf_LR} # 1e-2
          d1:
            parameters:
              - nerf_preproc.gaussian_splat_parameters.spherical_harmonics_d1
            lr: 0.005 # ${nerf_LR} # 1e-2
          positions:
            parameters:
              - preproc.named_params.offsets
            lr: 1e-4  

      model_rotation:
        groups:
          rotation:
            parameters:
                - nerf_preproc.gaussian_splat_parameters.rotation
            lr: 0.001 # ${nerf_LR} # 1e-2
      model_rotation_full:
        groups:
          rotation_full:
            parameters:
                - nerf_preproc.gaussian_splat_parameters.rotation
            lr: 0.01 # ${nerf_LR} # 1e-2
      model_opacity:
        groups:
          opacity:
            parameters:
              - nerf_preproc.gaussian_splat_parameters.opacity
            lr: 0.05 # ${nerf_LR} # 1e-2
      model_scaling:
        groups:
          scaling:
            parameters:
              - nerf_preproc.gaussian_splat_parameters.scaling
            lr: 0.005 # ${nerf_LR} # 1e-2
      model_scaling_full:
        groups:
          scaling_full:
            parameters:
              - nerf_preproc.gaussian_splat_parameters.scaling
            lr: 0.05 # ${nerf_LR} # 1e-2
      model_spherical_harmonics:
        groups:
          spherical_harmonics:
            parameters:
              - nerf_preproc.gaussian_splat_parameters.spherical_harmonics_dc
            lr: 0.0025 # ${nerf_LR} # 1e-2
      model_spherical_harmonics_full:
        groups:
          spherical_harmonics_full:
            parameters:
              - nerf_preproc.gaussian_splat_parameters.spherical_harmonics_dc
            lr: 0.025 # ${nerf_LR} # 1e-2
      model_d1:
        groups:
          d1:
            parameters:
              - nerf_preproc.gaussian_splat_parameters.spherical_harmonics_d1
            lr: 0.005 # ${nerf_LR} # 1e-2
      model_positions:
        groups:
          positions:
            parameters:
              - preproc.named_params.offsets
            lr: 1e-3 
      model_positions_full:
        groups:
          positions_full:
            parameters:
              - preproc.named_params.offsets
            lr: 1e-4  

  monads:
    # grid:
    #   mode: ndc
    #   width: 1920
    #   height: 1080
    #   depth: 1
    #   inclusive: true
    #   order: xy
    #   persistent: true
    ones:
      shape: [3, 1, 1]
      includes_batch: false
    random:
      shape: [3, 1, 1]
      mode: unit
      scale: 1.0
      includes_batch: false
    # parameter:
    #   shape: [6890, 4] # [6890, 3] # [6890, 1]
    #   init: zeros # randn
    named_params:
      parameters:
        offsets:
          shape: # [110210, 1] # [27554, 1] # [6890, 3] # [6890, 1]
            - ${NUM_SPLATS[${SUBDIV_INDEX}]} # ${NUM_SPLATS[1]} # ${NUM_SPLATS[${SUBDIV}]}
            - 1
          init: zeros # randn
        # latent:
        #   shape: [6890, 3] # [6890, 3] # [6890, 1]
        #   init: rand # randn
    # smpl:
    #   use_translation: false
    #   use_pose: false
    #   use_betas: false
    #   use_global_orientation: false
    #   gender: ${oc.env:SMPL_GENDER}
    #   model_path: ${oc.env:SMPL_ROOT}
    #   num_betas: 10
    #   # batch_size: 1
    opengl:
      width: 800 # 1920
      height: 1200
    # mesh_silhouette:
    #   width: 1920
    #   height: 1080 
    rotation3d:
      rotations: [180@y, 180@z] # [180@y, 180@z] # [180@z] # [180@y, 180@z]
    transform:
      transpose: true
      xyz_in_at: row
      xyz_out_at: row
    rasterize:
      decomposed: true
    # minmax_normalization:
    #   min_value: 1
    #   max_value: 13776
    gaussian_splat_parameters:
      num_splats: ${NUM_SPLATS[${SUBDIV_INDEX}]} # ${NUM_SPLATS[1]} # ${NUM_SPLATS[${SUBDIV}]} # 110210 # 27554
      skip_positions: true
      scale: 0.025 # 0.1 # 0.025 # 1.0
      opacity: 0.9 # 0.1 # null
      sh_degree: ${SH_DEGREE} # 3
    gaussian_splat_rasterizer:
      # prefiltered: false
      debug: false # true
      # scale_modifier: 1.0
      # width: null
      # height: null
      # background_color: black
  objectives:
    laplacian_smoothness:
      method: cotcurv
    cosine_distance:
      normalized: true
      epsilon: 1.0e-4
      dim: -1
    intersection_over_union:
      reduce: false