# @package _global_

SIL_W: ???
GEOMREG_W: ???
SURF_W: ???
AREA_W: ???
LAP_W: ???
NORMREG_W: ???
IMG_W: ???
SSIM_W: ???
UCF_W: ???

nerf_LR: ???
ucf_LR: ???

_moai_:
  _definitions_:
    _collections_:
      _optimizers_:
        optim_mesh: &optim_mesh
          # _type_: lbfgsls
          # _params_:
          #   max_iter: 15
          #   lr: 1.0
          #   tolerance_grad: 1e-09
          #   tolerance_change: 1e-12
          ##################
          _type_: adam
          _params_:
            lr: 1e-3
            amsgrad: true
            eps: 1e-9
            weight_decay: 0.0
            foreach: true # false
            capturable: false
            differentiable: false
            fused: false # true     
          ##################             
          # _type_: adamw # adam
          # _params_:
          #   lr: 1e-3
          #   amsgrad: true
          #   eps: 1e-12
          #   weight_decay: 1e-5 # 0.1 # 1e-6
          #   foreach: true # false
          #   capturable: false
          #   differentiable: false
          #   fused: false # true
          _groups_: [model1]
        optim_nerf: &optim_nerf
          _type_: adam
          _params_:
            lr: ${nerf_LR} # 1e-2
            amsgrad: false
            eps: 1e-9
            weight_decay: 0.0
            foreach: false # false
            capturable: false
            differentiable: false
            fused: false # true     
          _groups_: [model2]
        optim_ucf: &optim_ucf
          _type_: adam
          _params_:
            lr: ${ucf_LR} # 1e-2
            amsgrad: false
            eps: 1e-9
            weight_decay: 0.0
            foreach: false # false
            capturable: false
            differentiable: false
            fused: false # true     
          _groups_: [model3]
      _objectives_:
        reconstruction_loss_ucf:        
          passthrough:
            error: [ucf_log]
            _weight_:
              - ${UCF_W}
            _reduction_: [mean]
            _out_: [ucf_loss]
          # L1:
          #   gt: [masked_color]
          #   pred: [reconstructed_color]
          #   weights: [ucf_weights]
          #   _weight_:
          #     - ${IMG_W}              
          #   _reduction_: [mean] # [sum]
          #   _out_: [color_loss]
          structural_dissimilarity:
            gt: [masked_color]
            pred: [reconstructed_color]
            # mask: [mask]
            weights: [ucf_weights]
            _weight_:
              - ${SSIM_W}
            _reduction_: [mean] # [sum]
            _out_: [ssim_loss]          
        reconstruction_loss:
          # passthrough:
          #   error: [ucf_log]
          #   _weight_:
          #     - ${UCF_W}
          #   _reduction_: [mean]
          #   _out_: [ucf_loss]
          L1:
            gt: [masked_color]
            pred: [reconstructed_color]
            weights: [ucf_weights_d] # [mask] # [ucf_weights]
            _weight_:
              - ${IMG_W}              
            _reduction_: [mean] # [sum]
            _out_: [color_loss]
          structural_dissimilarity:
            gt: [masked_color]
            pred: [reconstructed_color]
            # mask: [mask]
            weights: [ucf_weights_d] # [mask] # [ucf_weights]
            _weight_:
              - ${SSIM_W}
            _reduction_: [mean] # [sum]
            _out_: [ssim_loss]          
        silhouette_loss:
          # L2:
          #  gt: [mask, null]
          #  pred: [reconstructed_color] #, offsets] # [color] # [reconstructed_color]
          #  _weight_: [1.0] #, 10000.0]
          #  _reduction_: [sum] #, sum]
          #  _out_: [recon] #, geom_reg]
          L2:
           gt: [null]
           pred: [offsets] # [color] # [reconstructed_color]
           _weight_: # [10.0] #, 10000.0]
            - ${GEOMREG_W}
           _reduction_: [mean] #, sum]
           _out_: [geom_reg]          
          intersection_over_union: # intersection_over_union: # L1:
           gt: [mask]
           pred: [silhouette]
           _weight_: # [0.1]
            - ${SIL_W}
           _reduction_: [sum] # [sum]
           _out_: [recon] 
          surface_normal_consistency:
            vertex_normals: [deformed_vertex_normals.vectors]
            faces: [faces]
            _weight_: # [10.0]
              - ${SURF_W}
            _reduction_: [mean]
            _out_: [surf_reg]
          laplacian_smoothness:
            vertices: [deformed_vertices]
            faces: [body.faces]
            _weight_: # [100.0]
              - ${LAP_W}
            _reduction_: [mean]
            _out_: [mesh_smooth]
          face_area_consistency:
            original: [original_vertex_normals.areas]
            deformed: [deformed_vertex_normals.areas]
            _weight_: # [1.0]
              - ${AREA_W}
            _reduction_: [mean]
            _out_: [face_area]
          # cosine_distance:
          #   pred: [original_vertex_normals.vectors]
          #   gt: [deformed_vertex_normals.vectors]
          #   _weight_: # [1.0]
          #     - ${NORMREG_W}
          #   _reduction_: [mean]
          #   _out_: [norm_reg]

          #TODO: chamfer distance