# @package _global_

experiment:
  name: RoGA_test_xh
  batch_size: 1
  workers: 0

engine:
  runner:
    deterministic: false # required for index add ops
    devices: 1
    num_sanity_val_steps: 0
    max_epochs: 20

  modules:
    precision:
      precision: highest # highest
    rerun:
      name: ${action}_${experiment.name}_${SUBJECT}_${TAKE}_${METHOD}
      memory_limit: 4GB
      world_coordinates: RUF # RDD # RUF
      # export: './rerun.rrd'
      # annotations:
      #   plots:
      #     - key: # 
      #       color: green
